BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "dummy" (
	"id"	INTEGER NOT NULL,
	"display_name"	TEXT NOT NULL,
	"pets"	INTEGER NOT NULL,
	PRIMARY KEY("id")
);
INSERT INTO "dummy" VALUES (0,'Eryn',303);
INSERT INTO "dummy" VALUES (1,'Nyre',8);
COMMIT;
